version: 2

models:
  - name: stg_marketing_campaigns
    description: Cleaned marketing campaigns source.
    columns:
      - name: campaign_id
        data_tests:
          - not_null
          - unique
      - name: campaign_name
        data_tests:
          - not_null

  - name: stg_marketing_campaign_products
    description: Cleaned marketing campaign products - mapping between campaigns and promoted book_ids.
    columns:
      - name: campaign_id
        data_tests:
          - not_null
      - name: book_id
        data_tests:
          - not_null

  - name: stg_marketing_campaign_daily_metrics
    description: Cleaned daily campaign metrics.
    columns:
      - name: campaign_id
        data_tests:
          - not_null
      - name: event_date
        data_tests:
          - not_null
