name: 'marketing_dbt'
version: '1.0.0'
profile: 'marketing_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_dbt:
    curated:
      +schema: marketing_curated
      +materialized: view
    published:
      +schema: marketing_published
      +materialized: table
