name: 'marketing_dbt'
version: '1.0.0'
profile: 'marketing_dbt'

models:
  marketing_dbt:
    staging:
      +schema: marketing_silver
      +materialized: view
    intermediate:
      +schema: marketing_silver
      +materialized: view
    marts:
      +schema: marketing_published
      +materialized: table